### PR TITLE
feat: add run script and package.json so that its only `npm i; npm start`

### PR DESCRIPTION
**Pull request by Toumash**
feat: add run script and package.json so that its only `npm i; npm start`

### CODE REVIEW

**Comment by ddikman** [comment]
@Toumash thank you so much for the PR! Glad to see anyone noticed the repo.

I'd be more than happy to merge this but to not leave ambiguous duplicate instructions, can you replace the older shell run-instruction (referencing the install of http-server) with this one?

**Comment by Toumash** [comment]
@ddikman done

**Comment by Toumash** [comment]
@ddikman i just saw that you have this hosted on the github pages. 

Please add the https://ddikman.github.io/firebase-jwt/ to the repo description!

**Review by ddikman — APPROVED** [review]
Great, thank you so much!

**Pull request merged**
